name: Tag Creation

on:
  push:
    branches:
      - main

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      updated: ${{ steps.release_tag.outputs.result != steps.previous_tag.outputs.result }}
      tag: ${{ steps.release_tag.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get previous tag
        id: previous_tag
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return release.data.tag_name;
          result-encoding: string
      - name: Get current image tag
        id: release_tag
        run: |
          echo result="$(grep ghcr.io/helmfile/helmfile Dockerfile | cut -d : -f 2)" >> "$GITHUB_OUTPUT"
      - name: Create tag that is same as base image tag
        if: steps.release_tag.outputs.result != steps.previous_tag.outputs.result
        run: |
          git tag ${{ steps.release_tag.outputs.result }}
          git push origin ${{ steps.release_tag.outputs.result }}

  call-release:
    needs: tag
    if: fromJSON(needs.tag.outputs.updated)
    permissions:
      packages: write
      contents: write
    uses: ./.github/workflows/release.yaml
    with:
      tag: ${{ needs.tag.outputs.tag }}
