name: Tag Creation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get previous tag
        id: previous_tag
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return release.tag_name;
          result-encoding: string
      - name: Get current image tag
        id: release_tag
        run: |
          echo version=$(cat Dockerfile | grep ghcr.io/helmfile/helmfile | cut -d : -f 2) >> $GITHUB_OUTPUT
      - name: Create tag that is same as base image tag
        if: steps.release_tag.outputs.version != steps.previous_tag.outputs.result
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: ${{ steps.release_tag.outputs.version }},
              message: "",
              object: ${{ github.sha }},
              type: "commit",
            });
